disabled_rules:
  - opening_brace
  - first_where
  - object_literal
  - sorted_imports
  - inclusive_language
  
opt_in_rules:
  - identifier_name
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicit_return
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - operator_usage_whitespace

  - array_init
  - contains_over_first_not_nil
  - joined_default_parameter
  - line_length
  - literal_expression_end_indentation
  - multiline_parameters
  - override_in_extension
  - pattern_matching_keywords
  - redundant_string_enum_value
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

  - nimble_operator
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class

  - closure_end_indentation
  - let_var_whitespace
  - implicitly_unwrapped_optional
  - private_outlet
  - strict_fileprivate
  - switch_case_on_newline
  
  - attributes
  - trailing_whitespace

included:
  - "App/MovieDB/Sources"

excluded:
  - Pods
  - fastlane
  - Guidelines
  - "App/MovieDB/Resources"
  - "App/MovieDB/Configs"
  - "App/Tests"
  - "App/DerivedData"
  - "App/MovieDB/Sources/Packages/Libraries/MDBCommon/Sources/MDBCommon/Mocks"
  - "App/MovieDB/Sources/Packages/Libraries/MDBCommon/.build"
  - "App/MovieDB/Sources/Packages/Libraries/MDBCommon/Tests"  
  - "App/MovieDB/Sources/Packages/Libraries/MDBCommonUI/Sources/MDBCommonUI/Mocks"
  - "App/MovieDB/Sources/Packages/Libraries/MDBCommon/.build"
  - "App/MovieDB/Sources/Packages/Libraries/MDBCommonUI/Tests"
  - "App/MovieDB/Sources/Packages/Libraries/MDBDataLayer/Sources/MDBDataLayer/Mocks"
  - "App/MovieDB/Sources/Packages/Libraries/MDBDataLayer/.build"
  - "App/MovieDB/Sources/Packages/Libraries/MDBDataLayer/Tests"
  - "App/MovieDB/Sources/Packages/Libraries/MDBModels/Sources/MDBModels/Mocks"
  - "App/MovieDB/Sources/Packages/Libraries/MDBModels/.build"
  - "App/MovieDB/Sources/Packages/Libraries/MDBModels/Tests"
  - "App/MovieDB/Sources/Packages/Libraries/MDBNetworking/Sources/MDBNetworking/Mocks"
  - "App/MovieDB/Sources/Packages/Libraries/MDBNetworking/.build"
  - "App/MovieDB/Sources/Packages/Libraries/MDBNetworking/Tests"
  - "App/MovieDB/Sources/Packages/Libraries/MDBServices/Sources/MDBServices/Mocks"
  - "App/MovieDB/Sources/Packages/Libraries/MDBServices/.build"
  - "App/MovieDB/Sources/Packages/Libraries/MDBServices/Tests"
  - "App/MovieDB/Sources/Packages/Libraries/MDBUtilities/Sources/MDBUtilities/Mocks"
  - "App/MovieDB/Sources/Packages/Libraries/MDBUtilities/.build"
  - "App/MovieDB/Sources/Packages/Libraries/MDBUtilities/Tests"
  - "App/MovieDB/Sources/Packages/Modules/MDBMain/Sources/MDBMain/Mocks"
  - "App/MovieDB/Sources/Packages/Modules/MDBMain/.build"
  - "App/MovieDB/Sources/Packages/Modules/MDBMain/Tests"
  - "App/MovieDB/Sources/Mocks"
  - "App/MovieDB/.build"
  - "swiftgen"

cyclomatic_complexity:
  warning: 25

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 700
  error: 1000

large_tuple: 
  warning: 4

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - Id
    - Ad

identifier_name:
  max_length:
    warning: 60
    error: 70
  excluded:
    - id
    - i

function_body_length:
  warning: 60
  error: 150

function_parameter_count:
  warning: 7
  error: 10

nesting:
  type_level:
    warning: 10
    error: 15

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
  
line_length:
  ignores_comments: true

attributes:
  always_on_same_line: ["@IBAction", "@IBOutlet", "@IBInspectable"]
  always_on_line_above: ["@IBDesignable", "@UIApplicationMain", "@discardableResult", "@objc"]

superfluous_disable_command: warning
force_unwrapping: error
trailing_semicolon: error

reporter: "xcode"

custom_rules:
  new_line_after_method_signature:
    include: "*.swift"
    name: "New line after method signature"
    regex: '\{\n\s*\n+\s*\w'
    message: "No new line after curly braces and before code"
    severity: warning
  new_line_between_braces:
    include: "*.swift"
    name: "New line after }"
    regex: '\}\n\s*\n+\s*\}'
    message: "No new line between curly braces"
    severity: warning
