///
/// @Generated by Mockolo
///

import Foundation
@testable import MDBCommon

public class DateFormatterLocatorProtocolMock: DateFormatterLocatorProtocol {
  public init() {}

  public private(set) var dateFormatterCallCount = 0
  public var dateFormatterHandler: (() -> (DateFormatter))?
  public func dateFormatter() -> DateFormatter {
    dateFormatterCallCount += 1
    if let dateFormatterHandler = dateFormatterHandler {
      return dateFormatterHandler()
    }
    fatalError("dateFormatterHandler returns can't have a default value thus its handler must be set")
  }
}
